rendered countries and their details
Developer-Kingz/metrics pull request #1
Opened 2023-08-16 21:09 UTC by Developer-Kingz

- created a home component to render list of countries from API
- added a details component to view more details about a country
- added redux slice for state management
- added linters

2023-08-16 23:11 UTC, mwanawabangona requested changes
Hi @Developer-Kingz ,

Good job so far!
![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
* ✅  No linter errors :heavy_check_mark:
* ✅  Repo looks professional :briefcase:
* ✅  Good quality commits


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-16 23:11 UTC, mwanawabangona commented on README.md
> +- Demo Video: [Demo Video] (https://www.loom.com/share/955c0e9e766d4a9eadc9094c6c9d5546)
- [ ] `Required`
- [ ] Amazing work 👏 
- [ ] The maximum length of the video is 5 minutes. ✔️ 
- [ ] The video contains a clear and objective description of the project in professional English ✔️ 
- [ ] The video contains a project demo, highlighting all the project features. ✔️ 
- [ ] The video highlights a piece of the code the `student` finds interesting or is proud of making. ❌ 
Please make the video contain highlights of a piece of code you find interesting or proud of making
According to the requirements. 🥂

2023-08-16 23:11 UTC, mwanawabangona commented on src/App.css
> +}
- [ ] `Required`
- [ ] Colors (select one main color for your website). ✔️ 
- [ ] Typography: font face, size and weight. ✔️ 
- [ ] However the  Layout: composition missed a few elements. 😞 
- [ ] kindly add the missing elements
- [ ] please sceenshoots below and the highlighted areas 👇 

`original`
![image](https://github.com/Developer-Kingz/metrics/assets/66230306/656d8985-5b64-41f6-bc86-23061fe3d266)

`your design`

![image](https://github.com/Developer-Kingz/metrics/assets/66230306/0a49ac16-5c34-43ef-8703-612048e0fed9)

2023-08-18 13:01 UTC, cynthiainga approved these changes
Hi @Developer-Kingz, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] All requested changes are implemented ✔️ 
- [ ] Correct Gitflow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-18 20:46 UTC, merged